using System;
using WUBS.Cct.DataExamples.DataBuilders;
using WUBS.Cct.DataExamples.Enums;
using WUBS.Cct.DataExamples.TestDataContainer;

namespace WUBS.Cct.DataExamples.Lockins.Disbursal
{
    public class LockInWithOverDisbursalThatCreatesTwoAdjustmentEntries_History : AbstractOrderData
    {
        public LockInWithOverDisbursalThatCreatesTwoAdjustmentEntries_History()
        {

            AddDatabase(new RLHistoryDB())
                //lockin
                .AddRow(new OrderHeaderBuilder<RLHistoryDB.TRRawHeader.TRRawHeaderRow>()
                    .OfType(OrderType.LockIn)
                    .WithOrderId(33040915)
                    .WithRelatedClientOrderId(33040929)
                    .WithItemCount(3)
                    .Ordered(DateTime.Parse("2017-05-24 04:33:01.280"))
                    .SettlementCurrency(CurrencyDefn.CHF)
                    .ForClient(797394)
                    .InApp(Application.GlobalPayPlus)
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.LockIn)
                    .WithId(55249411)
                    .ForOrderId(33040915)
                    .WithItemNumber(1)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(24026.74m)
                    .WithSettlementAmount(26424.6m)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .IsQuotedWithId(71369465)
                    .WithRate(new ItemRate(1.0998m, 0, 4, 1, null))
                    .WithWindowLength(2)
                    .WithReleaseDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.LockInAdjustment)
                    .WithId(55249447)
                    .ForOrderId(33040915)
                    .WithItemNumber(2)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(10000m)
                    .WithSettlementAmount(0)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .WithWindowLength(0)
                    .WithReleaseDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.LockInAdjustment)
                    .WithId(55249454)
                    .ForOrderId(33040915)
                    .WithItemNumber(2)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(0)
                    .WithSettlementAmount(10998)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .WithRate(new ItemRate(1.0998m, 0, 4, 1, null))
                    .WithWindowLength(0)
                    .Build())

                //disbursal
                .AddRow(new OrderHeaderBuilder<RLHistoryDB.TRRawHeader.TRRawHeaderRow>()
                    .OfType(OrderType.LockInDisbursal)
                    .WithOrderId(33040929)
                    .WithRelatedClientOrderId(33040915)
                    .WithItemCount(3)
                    .Ordered(DateTime.Parse("2017-05-24 04:34:22.493"))
                    .SettlementCurrency(CurrencyDefn.CHF)
                    .ForClient(797394)
                    .InApp(Application.GlobalPayPlus)
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.AchCredit)
                    .WithId(55249441)
                    .WithRelatedId(55249411)
                    .ForOrderId(33040929)
                    .WithItemNumber(1)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(6278.21m)
                    .WithSettlementAmount(6904.8m)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .IsQuotedWithId(0)
                    .WithRate(new ItemRate(1.0998m, 0, 4, 1, null))
                    .WithWindowLength(0)
                    .WithReleaseDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.AchCredit)
                    .WithId(55249442)
                    .ForOrderId(33040929)
                    .WithItemNumber(2)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(22354.4m)
                    .WithSettlementAmount(24585.35m)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .IsQuotedWithId(0)
                    .WithRate(new ItemRate(1.0998m, 0, 4, 1, null))
                    .WithWindowLength(0)
                    .WithReleaseDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .Build())
                .AddRow(new LineItemBuilder<RLHistoryDB.trrawdetail.trrawdetailRow>()
                    .OfType(ItemType.AchCredit)
                    .WithId(55249443)
                    .ForOrderId(33040929)
                    .WithItemNumber(2)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithTradeAmount(5394.13m)
                    .WithSettlementAmount(5932.45m)
                    .WithForeignAmountInSettlementCurrency(false)
                    .FundedBy(80)
                    .IsQuotedWithId(0)
                    .WithRate(new ItemRate(1.0998m, 0, 4, 1, null))
                    .WithWindowLength(0)
                    .WithReleaseDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .Build())
                .AddRow(new OrderDetailValueDateBuilder<RLHistoryDB.TRRawDetailValueDate.TRRawDetailValueDateRow>()
                    .WithRequestedValueDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .WithOrderDetailId(55249411)
                    .Build())
                .AddRow(new OrderDetailValueDateBuilder<RLHistoryDB.TRRawDetailValueDate.TRRawDetailValueDateRow>()
                    .WithRequestedValueDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .WithOrderDetailId(55249441)
                    .Build())
                .AddRow(new OrderDetailValueDateBuilder<RLHistoryDB.TRRawDetailValueDate.TRRawDetailValueDateRow>()
                    .WithRequestedValueDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .WithOrderDetailId(55249442)
                    .Build())
                .AddRow(new OrderDetailValueDateBuilder<RLHistoryDB.TRRawDetailValueDate.TRRawDetailValueDateRow>()
                    .WithRequestedValueDate(DateTime.Parse("2017-05-24 00:00:00.000"))
                    .WithOrderDetailId(55249443)
                    .Build());

            AddDatabase(new RueschlinkDB())
                .AddRow(new RueschlinkDB.DisbursableFund.DisbursableFundRow()
                {
                    ClientOrder_ID = 33040915,
                    OrderDetail_ID = 55249411,
                    Currency_ID = CurrencyDefn.EUR.ID,
                    OriginalAmount = 24026.74d,
                    RemainingAmount = 0
                });
                

            AddDatabase(new CrsDB())
                .AddRow(new QuoteBuilder<CrsDB.QuoteHistory.QuoteHistoryRow>()
                .WithQuoteId(71369465)
                    .WithTradeCurrency(CurrencyDefn.EUR)
                    .WithSettlementCurrency(CurrencyDefn.CHF)
                    .WithCustomerRate(1.0998m, 0)
                    .WithCostRate(1.092m, 0)
                    .WithForwardPoints(0.0001m, 0)
                    .WithRateMultiplier(1)
                    .Build())
                .AddRow(new CrossCurrencyBuilder()
                    .WithTargetCurrency(CurrencyDefn.EUR)
                    .WithBaseCurrency(CurrencyDefn.CHF)
                    .IsPerBase(0)
                    .NDecIn(4)
                    .NDecPer(4)
                    .Build());

            AddDatabase(new VMSDB());
        }
    }
}
