using WUBS.Cct.Treasury.DomainModel.Enums.Utility;

namespace WUBS.Cct.Treasury.DomainModel.Enums
{
    public enum OrderType
    {
        Undefined,
        [CctCode("PmtNew")]
        SellPaymentOrder,
        [CctCode("PmtNew_R")]
        SellPaymentOrderRepurchase,
        [CctCode("IncomingFunds")]
        BuyPaymentOrder,
        [CctCode("IncomingFunds_R")]
        IncomingFundsRepurchase,
        [CctCode("FWDSaleC")]
        SellForwardContract,
        [CctCode("FWDSaleC_R")]
        SellForwardContractRepurchase,
        [CctCode("FWDPurchC")]
        BuyForwardContract,
        [CctCode("FWDPurchC_R")]
        BuyForwardContractRepurchase,
        [CctCode("FuturePmt")]
        FuturePaymentsOrder,
        [CctCode("FuturePmt_R")]
        FuturePaymentsOrderRepurchase,
        [CctCode("MatureFutr")]
        MatureFuturePaymentsOrder,
        [CctCode("MatureFutr_R")]
        MatureFuturePaymentsOrderRepurchase,
        [CctCode("CrNote")]
        CreditNotesOrder,
        [CctCode("CrNote_R")]
        CreditNotesOrderRepurchase,
        [CctCode("SaleDisbur")]
        LockInDisbursalOrder,
        [CctCode("SaleDisbur_R")]
        LockInDisbursalOrderRepurchase,
        [CctCode("NostroPmt")]
        NostroPaymentOrder,
        [CctCode("NostroPmt_R")]
        NostroPaymentOrderRepurchase,
        [CctCode("IntoHldg")]
        IntoHolding,
        [CctCode("IntoHldg_R")]
        IntoHoldingRepurchase,
        [CctCode("SaleLockIn")]
        LockIn,
        [CctCode("SSTCharge")]
        SingleSidedTransactionCharge,
        [CctCode("RepurchPayout")]
        RepurchasePayout,
        [CctCode("FutureOH")]
        ScheduledPaymentOutOfHolding,
        [CctCode("SSTWriteOff")]
        SingleSidedTransactionWriteOff,
        [CctCode("MatureFwd")]
        MatureForward,
        [CctCode("FTSweep")]
        FtSweep,
        [CctCode("FTSweep_R")]
        FtSweepReversal,
        [CctCode("SSTPayout")]
        SingleSidedTransactionPayout,
        [CctCode("SSTPayout_R")]
        SingleSidedTransactionPayoutRepurchase,
        [CctCode("SSTPayment")]
        SingleSidedTransactionPayment,
        [CctCode("SSTWriteOff_R")]
        SingleSidedTransactionWriteOffReversal,
        [CctCode("SSTPayment_R")]
        SingleSidedTransactionPaymentReversal,
        [CctCode("SSTCharge_R")]
        SingleSidedTransactionChargeReversal,
        [CctCode("SaleLockIn_R")]
        LockInRepurchase
    }
}